environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

build: off

install:
  - python -m pip install -U pip setuptools six
  - pip install -U -r requirements.txt
  - pip install -U -e .

  - cd test && pip uninstall --yes zetup
  - pip install -e .[all]
  - pip install -U -r test-requirements.txt
  # - pip install -U tox

test_script:
  # - python setup.py pytest
  - py.test -vv --doctest-modules zetup test --cov zetup --cov test --cov-report term-missing
  # - python setup.py tox
  # - tox -r -v

  - zetup install
  # - zetup tox
