environment:
  matrix:
    - PY: C:\Python27\python.exe
    - PY: C:\Python27-x64\python.exe

    - PY: C:\Python35\python.exe
    - PY: C:\Python35-x64\python.exe

    - PY: C:\Python36\python.exe
    - PY: C:\Python36-x64\python.exe

    - PY: C:\Python37\python.exe
    - PY: C:\Python37-x64\python.exe

build: off

install:
  - cmd: |
        %PY% -m pip install -U pip setuptools six
        %PY% -m pip install -U -r requirements.txt
        %PY% -m pip install -U -e .

  - cmd: |
        cd test && %PY% -m pip uninstall --yes zetup && cd ..
        %PY% -m pip install -e .[all]
        %PY% -m pip install -U -r test-requirements.txt
        rem %PY% -m pip install -U tox

test_script:
  - cmd: |
        rem %PY% setup.py pytest
        %PY% -m pytest -vv --doctest-modules zetup test --cov zetup --cov test --cov-report term-missing
        rem %PY% setup.py tox
        rem %PY% -m tox -r -v

  - cmd: |
        %PY% -m zetup install
        %PY% -m zetup sdist
        rem %PY% -m zetup tox
