environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

build: off

install:
  - ps: |
        foreach ($args in
            "pip setuptools six",
            "-r requirements.txt",
            "-e .[all]"
        ) {
            python -m pip install -U $args.split()
        }

  - cd test && pip uninstall --yes zetup && cd .. && pip install -e .
  - pip install -U -r test-requirements.txt
  - pip install -U tox

test_script:
  - # python setup.py pytest
  - py.test -vv --doctest-modules zetup test --cov zetup --cov test --cov-report term-missing
  - # python setup.py tox
  - tox -r -v

  - zetup install
  - zetup tox
